export const POKEMON_TYPE_COLORS = {
  normal: '#edede4',
  fighting: '#f2d5d4',
  flying: '#ede8fc',
  poison: '#ecd8ec',
  ground: '#f8f2e0',
  rock: '#f0ecd7',
  bug: '#edf0d2',
  ghost: '#e2ddea',
  steel: '#f0f0f5',
  fire: '#fee1e1',
  water: '#e0e8fc',
  grass: '#daf5ef',
  electric: '#fff5db',
  psychic: '#fddde7',
  ice: '#eaf7f7',
  dragon: '#e2d7fd',
  dark: '#e2ddda',
  fairy: '#fbeaee',
};
